# Generated by Django 2.2.12 on 2021-10-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211017_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='', max_length=10, unique=True, verbose_name='昵称')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.CharField(default='无', max_length=1, verbose_name='性别')),
                ('id_card', models.CharField(default='', max_length=18, unique=True, verbose_name='身份证')),
                ('exp', models.IntegerField(default=0, verbose_name='经验')),
                ('bar_coin', models.IntegerField(default=0, verbose_name='趣味币')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
