# Generated by Django 2.2.12 on 2021-10-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211029_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_id',
            new_name='user',
        ),
    ]
