# Generated by Django 2.2.12 on 2021-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211029_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='portrait',
            field=models.FileField(default='img/head_portrait/01.png', upload_to='img/head_portrait/', verbose_name='头像'),
        ),
    ]
