# Generated by Django 2.2.12 on 2021-10-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_info_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='portrait',
            field=models.FileField(upload_to='img/head_portrait/', verbose_name='头像'),
        ),
    ]
