# Generated by Django 2.2.12 on 2021-10-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211017_2303'),
        ('article', '0002_auto_20211028_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(default='', max_length=10, unique=True, verbose_name='论坛名')),
                ('int', models.CharField(default='', max_length=38, verbose_name='简介')),
                ('id_card', models.CharField(default='', max_length=18, verbose_name='身份证')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'bar',
            },
        ),
    ]
