# Generated by Django 2.2.12 on 2021-11-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20211101_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
    ]
