# Generated by Django 2.2.12 on 2021-11-03 08:13

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211031_1840'),
        ('article', '0005_auto_20211102_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Bar'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'Reply',
            },
        ),
    ]
