# Generated by Django 2.2.12 on 2021-11-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_bar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='user_id',
            new_name='user',
        ),
    ]
