# Generated by Django 2.2.12 on 2021-11-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20211103_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Bar'),
        ),
    ]
