# Generated by Django 2.2.12 on 2021-11-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='portrait',
            field=models.FileField(default='', upload_to='img/bar_portrait/', verbose_name='主题头像'),
        ),
    ]
